im:
  tcpPort: 9001
  webSocketPort: 9101
  bossThreadSize: 1
  workThreadSize: 1
  heartBeatTime: 3000 # 心跳超时时间(毫秒)
  brokerId: 1001
  loginModel: 1
  logicUrl: http://127.0.0.1:8080

  redis:
    mode: single # 单机模式：single 哨兵模式：sentinel 集群模式：cluster
    database: 0
    password: abcde12345
    timeout: 3000 # 超时时间
    poolMinIdle: 8 #最小空闲数
    poolConnTimeout: 3000 # 连接超时时间(毫秒)
    poolSize: 10 # 连接池大小
    single: #redis单机配置
      address: 127.0.0.1:6379

  rabbitmq:
    host: 127.0.0.1
    port: 10040
    virtualHost: /
    userName: guest
    password: guest

  zkConfig:
    zkAddr: 127.0.0.1:2181
    zkConnectTimeOut: 5000