im:
  tcpPort: 9000
  webSocketPort: 9100
  bossThreadSize: 1
  workThreadSize: 1
  heartBeatTime: 3000 # 心跳超时时间(毫秒)
  brokerId: 1000
  loginModel: 1
  logicUrl: http://127.0.0.1:8000/v1/

  redis:
    mode: single # 单机模式：single 哨兵模式：sentinel 集群模式：cluster
    database: 0
    password: LJMredis1211@
    timeout: 3000 # 超时时间
    poolMinIdle: 8 #最小空闲数
    poolConnTimeout: 3000 # 连接超时时间(毫秒)
    poolSize: 10 # 连接池大小
    single: #redis单机配置
      address: 101.43.196.93:6379

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtualHost: /
    userName: guest
    password: guest

  zkConfig:
    zkAddr: 127.0.0.1:2181
    zkConnectTimeOut: 5000