

spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: abcde12345
    url: jdbc:mysql://127.0.0.1:3306/im-?serverTimezone=UTC&useSSL=false&characterEncoding=UTF8
    username: root


# logger配置
logging:
  config: classpath:logback-spring.xml

server:
  port: 8000

imconfig:
  # zookeeper 配置
  zkAddr: 127.0.0.1:2181
  zkConnectTimeOut: 5000
  # 路由的负载均衡算法, 1-随机，2-轮训，3 - hash
  imRouteWay: 3
  consistentHashWay: 1


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapperxml/**/*.xml
  global-config:
    db-config:
      update-strategy: NOT_EMPTY

